name = input("Enter your name:")
email = input("Enter your email:")
phone = input("Enter your phone:")
major = input("Enter your major:")
yearborn = int(input("Enter your year born:"))
gpa = float(input("Enter your GPA:"))
print("Name:", name)
print("Email:", email)
print("Phone:", phone)
print("Major", major)
print("Age", 2023-yearborn)
print("GPA:", gpa)
print("test")